version: '3.9'
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - caddy
      
    volumes:
      - .:/app

    labels:
      caddy: restaurant.tedstar25.homes 
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true