version: '3.9'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    networks:
      - caddy
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

    labels:
      caddy: restaurant.tedstar25.homes/server 
      caddy.reverse_proxy: "{{upstreams 80}}"


    #volumes:
      # Bind-mounts configuration
      #- ./node:/app
      # Ignoring any changes made in the "node_modules" folder
      #- ./app/node_modules

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - caddy
    volumes:
      - ./client/src:/app/src
    labels:
      caddy: restaurant.tedstar25.homes 
      caddy.reverse_proxy: "{{upstreams 80}}"






networks:
  caddy:
    external: true