version: '3.7'

#project_name: restaurant

services:
  restaurant_mail:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: restaurant_backend
    networks:
      - reverse_proxy
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  restaurant:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: restaurant
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ./client/src:/app/src

networks:
  reverse_proxy: 
    external: true
