version: '3.9'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
       # Host port:Container port
      - '3001:3001'
    networks:
      - caddy
    labels:
      caddy: restaurant.tedstar25.homes
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      # Bind-mounts configuration
      - ./node:/app
      # Ignoring any changes made in the "node_modules" folder
      - ./app/node_modules

  client:
    image: restaurant
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - caddy
    stdin_open: true

networks:
  caddy:
    external: true