version: '3.7'

x-compose-config:
  project_name: restaurant

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3001:3001'

    networks:
      - restaurant
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '4000:3000'
    networks:
      - restaurant
    volumes:
      - ./client/src:/app/src


networks:
  restaurant:
    driver: bridge
