version: '3.7'

x-compose-config:
  project_name: restaurant


services:

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend

    depends_on:
      - backend

    networks:
      - restaurant
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend

    networks:
      - restaurant
    volumes:
      - ./client/src:/app/src



networks:

  restaurant:
    driver: bridge


  caddy:
    external: true