version: '3.7'

services:
  restaurant_be:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always

    networks:
      - restaurant
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  restaurant_fe:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - restaurant
      - reverse_proxy
    volumes:
      - ./client/src:/app/src


networks:
  restaurant:
    driver: bridge

  reverse_proxy: 
    external: true
