version: '3.9'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    networks:
      - caddy
    env_file:
      - ./server/.env 

    #volumes:
      # Bind-mounts configuration
      #- ./node:/app
      # Ignoring any changes made in the "node_modules" folder
      #- ./app/node_modules

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - caddy
    labels:
      caddy: restaurant.tedstar25.homes www.restaurant.tedstar25.homes
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.header.Access-Control-Allow-Origin: https://restaurant.tedstar25.homes http://restaurant.tedstar25.homes https://test.tedstar25.homes http://test.tedstar25.homes http://localhost
      caddy.header.Access-Control-Allow-Methods: POST, PUT



networks:
  caddy:
    external: true