version: '3.9'
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    networks:
      - caddy
      
    env_file:
      - ./.env
    volumes:
      - .:/app

    labels:
      caddy: test.tedstar25.homes 
      caddy.reverse_proxy: "{{upstreams 80}}"








networks:
  caddy:
    external: true